%import common.NUMBER
%import common.WS
%ignore WS

start : expr (";" expr)* ";"*

expr: product 
     | expr "+" product -> add 
     | expr "-" product -> sub

?product: atom 
        | product "*" atom -> mul 
        | product "/" atom -> div

?atom: NUMBER -> number 
     | "-" atom -> neg
     | "+" atom -> pos
     | paren
     | dice

paren: "(" expr ")"

dice: dice_amount "d" dice_power
dice_power: [NUMBER]
dice_amount: [NUMBER]
